// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/minio/file": {
            "get": {
                "description": "get document by bucket and filename",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "minio"
                ],
                "summary": "get document",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filename",
                        "name": "Filename",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "BucketName",
                        "name": "BucketName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.DownloadFileResult"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/main.DownloadFileResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.DownloadFileResult"
                        }
                    }
                }
            },
            "post": {
                "description": "get document by bucket and filename",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "minio"
                ],
                "summary": "get document",
                "parameters": [
                    {
                        "description": "upload file",
                        "name": "filedata",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.UploadFileInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.UploadFileResult"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/main.UploadFileResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.UploadFileResult"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.DownloadFileResult": {
            "type": "object",
            "properties": {
                "base64Content": {
                    "type": "string"
                },
                "contentType": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "fileSize": {
                    "type": "integer"
                },
                "humanError": {
                    "type": "string"
                }
            }
        },
        "main.UploadFileInput": {
            "type": "object",
            "properties": {
                "base64Content": {
                    "type": "string"
                },
                "bucketName": {
                    "type": "string"
                },
                "contentType": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "filesize": {
                    "type": "integer"
                }
            }
        },
        "main.UploadFileResult": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "etag": {
                    "type": "string"
                },
                "humanError": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "This is a sample server celler server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
